name: t3-ci
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Use Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '14.X'
      - name: install deps
        run: npm install
      - name: db
        run: npx prisma db push
      - name: build app
        run: npm run build
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          source: out/*
          host: '${{ secrets.REMOTE_HOST }}'
          target: '${{ secrets.REMOTE_PATH }}'
          port: 22
          username: '${{ secrets.USER_NAME }}'
          key: '${{ secrets.SSH_KEY }}'
